package university;

public enum FacultyName {
    MATHEMATICS, PHYSICS, COMPUTER_SCIENCE, CHEMISTRY, BIOLOGY, LITERATURE, ECONOMICS, HISTORY, GEOGRAPHY, SOCIOLOGY,
    PSYCHOLOGY, JURISPRUDENCE, PHYSICAL_EDUCATION
}
